### ISSUE TITLE
Writing Checklist

### ISSUE THREAD

**Issue by yardasol** [arfc/2022-yardas-student-conference#1]
- [x] Run a spell checker.
- [x] The Oxford comma must appear in lists ("lions, tigers, and bears.")
- [x] Do not use the word "where" unless referring to a location (try "such that" or "in which").
- [x] Do not use the word "when" unless referring to a time (try "if" instead).
- [x] Only use "large" when referring to size.
- [x] Use of "very" suggests that a cooler word exists.
- [x] Other misused/overused words include: code, input, output, different, value, amount, model.
- [x] Articles such as "a" "the" "some" "any" and "each" must appear where necessary.
- [x] All subjects match the plurality of their verbs ( no: "Apples is tasty" yes: "Apples are tasty").
- [x] Avoid run-on sentences.
- [x] Clunky nouns -> spunky verbs (progression, expression --> progress, express)
- [x] Reduce vague words (important, methodologic).
- [ ] Reduce acronyms / jargon
- [x] Expand all acronyms on first use (rely on the acros.tex file and glossaries package to automate this).
- [ ] Get rid of unnecessary prepositional phrases -- author clearing throat (It can be shown that)
- [x] Get rid of extraneous adverbs (very, really, quite, basically, generally)
- [x] Get rid of there are / there is
- [x] Turn negatives to positives (she was not often right -> she was usually wrong).
- [x] Get rid of extraneous prepositions (the meeting happened on monday -> the meeting happened monday) (they agreed that it was true -> they agreed it was true)
- [x] Get rid of passive voice (is/was/are/were/be/been/am + past tense verb), replace with active voice
- [x] Use strong verbs (use sparingly: is, are, was, were, be, been, am).
- [x] Avoid turning verbs into nouns ("obtain estimates of" -> "estimates"; "provides a description of" -> "describes").
- [x] Don't bury the verb (keep the predicate close to the subject at the beginning of the sentence).
- [x] Data is plural (the data are critical).
- [x] Compare to (point out similarities between different things) vs.  compared with (point out differences between similar things)
- [x] Punctuation helps you to vary your sentence structure.
- [x] Power to separate in increasing power: comma, colon, dash, parentheses, semicolon, period
- [x] In increasing order of formality: dash, parentheses, all of the others. Don't overdo it with the dash and parentheses
- [x] Semicolon: connects two independent clauses. OR separates items when the list contain internal punctuation.
- [x] Use a colon to introduce a list, quote, explanation, conclusion, or amplification.
- [x] If there's a list in a sentence, it shouldn't come before the colon.
- [x] Use a dash to insert something in the middle of the sentence. Don't overuse it.
- [x] Always use isotopic notation like `$^{239}Pu$`. Never `$Pu-239$` or `$plutonium-239$`.
- [x] Elemental symbols (Ni, Li, Na, Pu) are capitalized, but their names are not (nickel, lithium, sodium, plutonium).
- [x] A phrase of the form <verb>ion of <noun> is probably clearer as <noun> <verb>ion. (For example, convert "calculation of velocity" to "velocity calculation".)
- [x] Cite all images, methods, software, and empirical data. Review [the principles](https://www.force11.org/software-citation-principles) and try [CiteAs](https://citeas.org/about) if necessary.
- [x] Refer to software consistently by name.
- [x] Each sentence/paragraph should logically follow the previous sentence/paragraph.
- [x] Be concise and direct.
- [x] When giving examples, use variables instead of numbers and use symbolic math instead of acronyms.
- [x] When you introduce words or phrases that are unusual or likely to be unfamiliar to the reader, italicize them.
- [x] If you use an uncommon word, either consider changing it or define it in its first usage.
- [x] You're a human writing for other humans: Make the wording exciting, and remember some people reading it won't know as much jargon as you do.
- [x] Vary your sentence structure to keep readers engaged.

**Comment by yardasol** [comment]
@nsryan2 can you make a new branch called `nsryan-review` or something similar and make a PR into `main` with edits and suggestions?

**Comment by nsryan2** [comment]
[olek_ans22sc_abstract.pdf](https://github.com/arfc/2022-yardas-student-conference/files/7996676/olek_ans22sc_abstract.pdf)
Hey Olek, very solid abstract! I had some issue in getting everything to render, but your text was really good. I look forward to your presentation. I can make suggestions in your tex files, but if you want to get a jump on it (I probably won't be able to get around to that until later today or early tomorrow) I attached my notes.

**Comment by yardasol** [comment]
I'll make a PR adjusting for your current comments and then you can review and do in-text comments that way

**Comment by katyhuff** [comment]
This seems complete -- should it be closed @yardasol @nsryan2  ?

**Comment by yardasol** [comment]
Yes we can close this!
